apiVersion: v1
kind: Secret
metadata:
  # this is the jenkins id.
  name: "molgenis-jenkins-github-token-secret"
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    jenkins.io/credentials-type: "secretText"
  annotations: {
    jenkins.io/credentials-description : "Oauth token for the {{.Values.secret.gitHub.user}} GitHub user"
  }
type: Opaque
data:
  text: {{ .Values.secret.gitHub.token | b64enc | quote }}