apiVersion: v1
kind: Secret
metadata:
  # this is the jenkins id.
  name: molgenis-jenkins-registry-secret
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    jenkins.io/credentials-type: "usernamePassword"
  annotations: {
    jenkins.io/credentials-description : "(deprecated by vault) Account used in pipeline builds to push docker images to registry.molgenis.org."
  }
type: Opaque
data:
  username: {{ .Values.secret.registry.user | b64enc | quote }}
  password: {{ .Values.secret.registry.password | b64enc | quote }}