---
nfs-subdir-external-provisioner:
  enabled: true
  nfs:
    server: 192.168.64.160
    path: /
  storageClass:
    defaultClass: true
    pathPattern:

storage:
  archived:
    mountPath: /persistentvolumes
    cleanup:
      enabled: true