apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Values.nexus.name }}
  labels:
    app: {{ .Values.nexus.name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.nexus.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Values.nexus.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.nexus.name }}
      creationTimestamp: null
    spec:
      volumes:
      - name: {{ .Values.persistance.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistance.name }}
      restartPolicy: {{ .Values.nexus.restartPolicy }}
      initContainers:
      - name: volume-mount-nexus
        image: busybox
        command: ["sh", "-c", "chown -R 200:200 {{ .Values.persistance.mountPath }}"]
        volumeMounts:
        - name: {{ .Values.persistance.name }}
          mountPath: "{{ .Values.persistance.mountPath }}"
      containers:
      - name: {{ .Values.nexus.name }}
        image: "{{ .Values.nexus.image.repository }}:{{ .Values.nexus.image.tag }}"
        imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nexus.port.ui }}
        - containerPort: {{ .Values.nexus.port.docker }}
        volumeMounts:
        - name: {{ .Values.persistance.name }}
          mountPath: "/nexus-data"

