apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "molgenis-rserve.fullname" . }}
  labels:
{{ include "molgenis-rserve.labels" . | indent 4 }}
spec:
  strategy:
    type: {{ .Values.strategy }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "molgenis-rserve.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "molgenis-rserve.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "molgenis-rserve.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.debug }}
          env:
            - name: "DEBUG"
              value: "TRUE"
          {{- end }}
          ports:
            - name: rserve
              containerPort: 6311
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: rserve
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: rserve
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
          - name: pv-rserve-tmp
            mountPath: /tmp/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: pv-rserve-tmp
          emptyDir: {}
          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
