clusterName: molgenis

replicaCount: 1

service:
  type: ClusterIP
  port: 9300

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  path: /
  tls: []

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 7.16.2
  pullPolicy: IfNotPresent

javaOpts: "-Xms1g -Xmx1g"

# Allows you to add any config files in /usr/share/elasticsearch/config/
# such as elasticsearch.yml and log4j2.properties
esConfig: {}
#  elasticsearch.yml: |
#    key:
#      nestedkey: value
#  log4j2.properties: |
#    key = value

resources:
  limits:
    cpu: 1
    memory: 3Gi
  requests:
    cpu: 100m
    memory: 1500Mi
persistence:
  # existingClaim: ""
  enabled: true
  accessMode: ReadWriteMany
  size: 10Gi
  storageClass: ""

nodeSelector: {}

tolerations: []

affinity: {}
