apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  labels:
{{ include "molgenis-armadillo.labels" . | indent 4 }}
data:
  adminusername: {{ .Values.server.admin.username | quote }}
  "application.json": {{ toJson .Values.server.config | quote }}