{{- if .Values.ingress.enabled -}}
{{- $fullName := include "molgenis-armadillo.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "molgenis-armadillo.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := $.Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
    - host: {{ template "molgenis-armadillo.hostname" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
    - host: {{ template "armadillo-minio.hostname" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "call-nested" (list $ "minio" "minio.fullname") }}
                port:
                  number: {{ .Values.minio.service.port }}
{{- if index .Values "molgenis-auth" "enabled" }}
    - host: {{ template "armadillo-auth.hostname" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "call-nested" (list $ "molgenis-auth" "molgenis-auth.fullname") }}
                port:
                  number: {{ index .Values "molgenis-auth" "service" "port" }}
{{- end }}
{{- end }}
