apiVersion: v1
kind: Secret
metadata:
  name: {{ include "molgenis-armadillo.fullname" . }}
  labels:
{{ include "molgenis-armadillo.labels" . | indent 4 }}
type: Opaque
data:
  adminpassword: {{ $.Values.server.admin.password | b64enc | quote }}
  seed: {{ $.Values.server.seed | toString | b64enc | quote}}