# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: test

strategy:
  type: Recreate
restartPolicy: Always

readinessPath: '/@molgenis-ui/legacy-lib/dist/context.css'

image:
  repository: registry.hub.docker.com
  name: molgenis/molgenis-frontend
  tag: latest
  pullPolicy: Always

service:
  name: molgenis-frontend
  type: ClusterIP
  port: 80

proxy:
  backend:
    service:
      enabled: true
  #
  # If you want to connect inside the same cluster you can specify the targetNamespace and targetRelease.
  # This way the service will be resolved inside the cluster.
  #
  #      targetNamespace:
  #      targetRelease:
  # When you connect to an external MOLGENIS backend you can set proxy.backend.service.enabled=false and specify the backend url.
  #
  #    url: https://master.dev.molgenis.org

  frontend:
    # Add and replace files in the conf.d dir of the frontend container
    # custom.conf: |-
    #   location /my-app/ {
    #     proxy_pass https://my-domain.ext/my-app/;
    #   }
    # experimental.conf: |-
    #   location /@molgenis-experimental/ {
    #     proxy_pass https://unpkg.com/@molgenis-experimental/;
    #     proxy_intercept_errors on;
    #     recursive_error_pages on;
    #     error_page 301 302 307 = @handle_redirect;
    #   }

ingress:
  enabled: true
  path: /
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 0
  basicAuth:
    enabled: false
    realm: "Authentication Required"
    auth: "xxxx"

resources: {}

nodeSelector:
  deployPod: "true"

tolerations: []

affinity: {}
