# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: production

strategy:
  type: Recreate
restartPolicy: Always

image:
  repository: registry.molgenis.org
  name: molgenis/molgenis-frontend
  tag: "PR-44-45"
  pullPolicy: Always

service:
  name: molgenis-frontend
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
  - name: frontend.molgenis.org
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
