# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

strategy:
  type: Recreate
restartPolicy: Always

image:
  repository: registry.molgenis.org
  name: molgenis/molgenis-frontend
  tag: "dev"
  pullPolicy: Always

service:
  name: molgenis-frontend
  type: ClusterIP
  port: 80

backend:
  url: https://latest.test.molgenis.org

environment: dev

ingress:
  enabled: true

nodeSelector: {}

tolerations: []

affinity: {}
