apiVersion: v1
kind: Service
metadata:
  name: {{ template "molgenis.fullname" . }}
  labels:
    app: {{ template "molgenis.name" . }}
    chart: {{ template "molgenis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.firewall.enabled }}
  loadBalancerSourceRanges:
{{- if .Values.service.firewall.kind eq "umcg" }}
    {{- range $index, $rule := .Values.service.firewall.umcg.rules }}
    - {{ $rule }}
    {{- end }}
{{- else }}
    {{- range $index, $rule := .Values.service.firewall.cluster.rules }}
    - {{ $rule }}
    {{- end }}
{{- end }}
{{- end }}
  ports:
    - name: molgenis
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "molgenis.name" . }}
    release: {{ .Release.Name }}
