apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: backup
  namespace: "vault-operator"
spec:
  etcdEndpoints: ["https://vault-etcd-client:2379"]
  storageType: ABS
  clientTLSSecret: vault-etcd-client-tls
  abs:
    path: vault/backup
    absSecret: abs