jenkins:
  Master:
    HostName: jenkins.molgenis.org
    ServiceType: ClusterIP
    InstallPlugins:
      - kubernetes:1.8.4
      - workflow-aggregator:2.5
      - workflow-job:2.21
      - credentials-binding:1.16
      - git:3.9.1
      - github-branch-source:2.3.6
      - kubernetes-credentials-provider:0.9
    Jobs: |-
      molgenis: |-
        <?xml version='1.1' encoding='UTF-8'?>
        <jenkins.branch.OrganizationFolder plugin="branch-api@2.0.20">
          <actions/>
          <description></description>
          <properties>
            <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.3.1">
              <dockerLabel></dockerLabel>
              <registry plugin="docker-commons@1.13"/>
            </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
            <jenkins.branch.NoTriggerOrganizationFolderProperty>
              <branches>.*</branches>
            </jenkins.branch.NoTriggerOrganizationFolderProperty>
          </properties>
          <folderViews class="jenkins.branch.OrganizationFolderViewHolder">
            <owner reference="../.."/>
          </folderViews>
          <healthMetrics>
            <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.5.1">
              <nonRecursive>false</nonRecursive>
            </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
          </healthMetrics>
          <icon class="jenkins.branch.MetadataActionFolderIcon">
            <owner class="jenkins.branch.OrganizationFolder" reference="../.."/>
          </icon>
          <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.5.1">
            <pruneDeadBranches>true</pruneDeadBranches>
            <daysToKeep>-1</daysToKeep>
            <numToKeep>-1</numToKeep>
          </orphanedItemStrategy>
          <triggers>
            <com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger plugin="cloudbees-folder@6.5.1">
              <spec>H H * * *</spec>
              <interval>86400000</interval>
            </com.cloudbees.hudson.plugins.folder.computed.PeriodicFolderTrigger>
          </triggers>
          <disabled>false</disabled>
          <navigators>
            <org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator plugin="github-branch-source@2.3.6">
              <repoOwner>molgenis</repoOwner>
              <credentialsId>molgenis-jenkins-github-secret</credentialsId>
              <traits>
                <org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
                  <strategyId>1</strategyId>
                </org.jenkinsci.plugins.github__branch__source.BranchDiscoveryTrait>
                <org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
                  <strategyId>1</strategyId>
                </org.jenkinsci.plugins.github__branch__source.OriginPullRequestDiscoveryTrait>
                <org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
                  <strategyId>1</strategyId>
                  <trust class="org.jenkinsci.plugins.github_branch_source.ForkPullRequestDiscoveryTrait$TrustPermission"/>
                </org.jenkinsci.plugins.github__branch__source.ForkPullRequestDiscoveryTrait>
              </traits>
            </org.jenkinsci.plugins.github__branch__source.GitHubSCMNavigator>
          </navigators>
          <projectFactories>
            <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory plugin="workflow-multibranch@2.19">
              <scriptPath>Jenkinsfile</scriptPath>
            </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProjectFactory>
          </projectFactories>
          <buildStrategies/>
        </jenkins.branch.OrganizationFolder>
    # Kubernetes secret that contains a 'credentials.xml' for Jenkins
    # CredentialsXmlSecret: jenkins-credentials
    # Kubernetes secret that contains files to be put in the Jenkins 'secrets' directory,
    # useful to manage encryption keys used for credentials.xml for instance (such as
    # master.key and hudson.util.Secret)
    # SecretsFilesSecret: jenkins-secrets
    CustomConfigMap: true
  rbac:
    install: true
  Pods:
    molgenis:
      Label: molgenis
      NodeUsageMode: NORMAL
      volumes:
        - type: HostPath
          hostPath: "/var/run/docker.sock"
          mountPath: "/var/run/docker.sock"
        - type: Secret
          secretName: molgenis-pipeline-file-secret
          mountPath: "/root/.m2"
      Containers:
        maven:
          Image: "registry.webhosting.rug.nl/molgenis/maven"
          TTY: true
          resources:
            requests:
              cpu: "1000m"
            limits:
              memory: "1Gi"
        alpine:
          Image: "spotify/alpine"
          TTY: true
        elasticsearch:
          Image: "elasticsearch"
          ImageTag: "5.5.1"
          TTY: true
          Ports:
            - name: rest
              containerPort: "9200"
              hostPort: "9200"
            - name: api
              containerPort: "9300"
              hostPort: "9300"
        postgres:
          Image: "postgres"
          ImageTag: "9.6-alpine"
          TTY: true
          Ports:
            - name: postgres
              containerPort: "5432"
              hostPort: "5432"
      EnvVars:
        - type: Secret
          key: PGP_PASSPHRASE
          secretName: molgenis-pipeline-env-secret
          secretKey: pgpPassphrase
        - type: KeyValue
          key: PGP_SECRETKEY
          value: "keyfile:/root/.m2/key.asc"
        - type: Secret
          key: SONAR_TOKEN
          secretName: molgenis-pipeline-env-secret
          secretKey: sonarToken
        - type: Secret
          key: CODECOV_TOKEN
          secretName: molgenis-pipeline-env-secret
          secretKey: codecovToken
        - type: Secret
          key: GITHUB_TOKEN
          secretName: molgenis-pipeline-env-secret
          secretKey: githubToken
      # If needed
      # ImagePullSecret: jenkins
      NodeSelector: {}
PipelineSecrets:
  Env:
    # Set to false to keep existing secret
    Replace: true
    # Passphrase for the pgp private key file, prefixed with literal:
    PGPPassphrase: literal:xxxx
    # Token for codecov.io service
    CodecovToken: xxxx
    # Token for github bot account
    GitHubToken: xxxx
    # Token for sonarcloud.io
    SonarToken: xxxx
  File:
    # Set to false to keep existing secret
    Replace: true
    # PGP Private key in ascii format used to sign artifacts
    PGPPrivateKeyAsc: |-
      -----BEGIN PGP PRIVATE KEY BLOCK-----
      xxxxx
      -----END PGP PRIVATE KEY BLOCK-----
    # maven.settings file
    MavenSettingsXML: |-
      <settings>
        <localRepository>${user.home}/.mvnrepository</localRepository>
        <interactiveMode>false</interactiveMode>
        <mirrors>
          <mirror>
            <id>nexus</id>
            <mirrorOf>external:*</mirrorOf>
            <url>https://registry.molgenis.org/repository/maven-central/</url>
          </mirror>
        </mirrors>
        <servers>
          <!-- for snapshot builds of the master -->
          <server>
            <id>sonatype-nexus-staging</id>
            <username>molgenis</username>
            <password>xxxx</password>
          </server>
          <server>
            <id>local-nexus</id>
            <url>https://registry.molgenis.org/repository/maven-snapshots/</url>
            <username>admin</username>
            <password>xxxxx</password>
          </server>
          <!-- for docker images-->
          <server>
            <id>registry.molgenis.org</id>
            <username>admin</username>
            <password>xxxx</password>
          </server>
        </servers>
      </settings>