jenkins:
  Master:
    HostName: jenkins.molgenis.org
    ServiceType: ClusterIP
    InstallPlugins:
      - kubernetes:1.8.4
      - workflow-aggregator:2.5
      - workflow-job:2.21
      - credentials-binding:1.16
      - git:3.9.1
    Jobs: |-
      molgenis: |-
        <?xml version='1.1' encoding='UTF-8'?>
        <org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject plugin="workflow-multibranch@2.19">
            <actions/>
            <description></description>
            <properties>
                <org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig plugin="pipeline-model-definition@1.3">
                    <dockerLabel></dockerLabel>
                    <registry plugin="docker-commons@1.13"/>
                </org.jenkinsci.plugins.pipeline.modeldefinition.config.FolderConfig>
            </properties>
            <folderViews class="jenkins.branch.MultiBranchProjectViewHolder" plugin="branch-api@2.0.20">
                <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
            </folderViews>
            <healthMetrics>
                <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.5.1">
                    <nonRecursive>false</nonRecursive>
                </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
            </healthMetrics>
            <icon class="jenkins.branch.MetadataActionFolderIcon" plugin="branch-api@2.0.20">
                <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
            </icon>
            <orphanedItemStrategy class="com.cloudbees.hudson.plugins.folder.computed.DefaultOrphanedItemStrategy" plugin="cloudbees-folder@6.5.1">
                <pruneDeadBranches>true</pruneDeadBranches>
                <daysToKeep>-1</daysToKeep>
                <numToKeep>-1</numToKeep>
            </orphanedItemStrategy>
            <triggers/>
            <disabled>false</disabled>
            <sources class="jenkins.branch.MultiBranchProject$BranchSourceList" plugin="branch-api@2.0.20">
                <data>
                    <jenkins.branch.BranchSource>
                        <source class="jenkins.plugins.git.GitSCMSource" plugin="git@3.9.1">
                            <id>a1f535cd-ab83-4d42-8993-0c3e59cf139f</id>
                            <remote>http://github.com/molgenis/molgenis.git</remote>
                            <credentialsId></credentialsId>
                            <traits>
                                <jenkins.plugins.git.traits.BranchDiscoveryTrait/>
                            </traits>
                        </source>
                        <strategy class="jenkins.branch.DefaultBranchPropertyStrategy">
                            <properties class="empty-list"/>
                        </strategy>
                    </jenkins.branch.BranchSource>
                </data>
                <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
            </sources>
            <factory class="org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory">
                <owner class="org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject" reference="../.."/>
                <scriptPath>Jenkinsfile</scriptPath>
            </factory>
        </org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject>
    # Kubernetes secret that contains a 'credentials.xml' for Jenkins
    # CredentialsXmlSecret: jenkins-credentials
    # Kubernetes secret that contains files to be put in the Jenkins 'secrets' directory,
    # useful to manage encryption keys used for credentials.xml for instance (such as
    # master.key and hudson.util.Secret)
    # SecretsFilesSecret: jenkins-secrets
    CustomConfigMap: true
  rbac:
    install: true
  # A second agent to configure a second pod template
  Pod:
    Enabled: true
    Image: "webhost12.service.rug.nl/molgenis/molgenis-maven"
    ImageTag: latest
  # ImagePullSecret: jenkins
    Label: "molgenis-maven"
    Privileged: false
    Cpu: "200m"
    Memory: "256Mi"
    # You may want to change this to true while testing a new image
    AlwaysPullImage: true
    Command: "/bin/sh -c"
    Args: "cat"
    TTY: true
    # You can define the volumes that you want to mount for this container
    # Allowed types are: ConfigMap, EmptyDir, HostPath, Nfs, Pod, Secret
    # Configure the attributes as they appear in the corresponding Java class for that type
    # https://github.com/jenkinsci/kubernetes-plugin/tree/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes
    volumes:
      - type: "HostPath"
        mountPath: "/var/run/docker.sock"
        hostPath: "/var/run/docker.sock"
    # - type: Secret
    #   secretName: mysecret
    #   mountPath: /var/myapp/mysecret
    NodeSelector: {}
    # Key Value selectors. Ex:
    # jenkins-agent: v1
