apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "molgenis.fullname" . }}
  labels:
    app: {{ template "molgenis.name" . }}
    chart: {{ template "molgenis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "molgenis.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "molgenis.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: molgenis
        {{- with .Values.molgenis }}
          image: {{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            - name: molgenis.home
              value: /home/molgenis
            - name: opencpu.uri.host
              value: {{ .opencpu }}
            - name: elasticsearch.transport.addresses
              value: {{ $.Release.Name }}-molgenis-elasticsearch:9300
            - name: elasticsearch.cluster.name
              value: {{ index $.Values "molgenis-elasticsearch" "master" "clusterName" }}
            - name: db_uri
              value: jdbc:postgresql://{{ $.Release.Name -}}-postgresql/{{ $.Values.postgresql.postgresDatabase }}
            - name: db_user
              value: {{ $.Values.postgresql.postgresqlUsername }}
            - name: db_password
              value: "{{ $.Values.postgresql.postgresqlPassword }}"
            - name: admin.password
              value: "{{ .adminPassword }}"
            - name: python_script_executable
              value: {{ $.Values.molgenis.python.executable }}
            {{- if .sentry }}
            - name: SENTRY_SERVERNAME
              value: {{ template "molgenis.hostname" $ }}
            - name: SENTRY_RELEASE
              value: {{ .image.name }}@{{ .image.tag }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .environment }}
            {{- range $key, $value := default dict .sentry }}
            - name: SENTRY_{{ $key | snakecase | upper }}
              value: {{ $value }}
            {{- end }}
            {{- end}}
            {{- with $.Values.minio }}
            - name: minio_bucket_name
              value: {{ .defaultBucket.name }}
            - name: minio_endpoint
              value: http://{{ template "minio.fullname" $ }}:{{ .service.port }}
            - name: minio_access_key
              value: {{ .accessKey }}
            - name: minio_secret_key
              value: {{ .secretKey }}
            {{- end}}
            - name: CATALINA_OPTS
              value: -XX:MaxRAMFraction=2
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: pv-molgenis
            mountPath: /home/molgenis
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 25
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/v2/version
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{ template "molgenis.resources" $ }}
        {{- end }}
      volumes:
        - name: pv-molgenis
        {{ - if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "myapp.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
