kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistance.name }}
spec:
  storageClassName: nfs-class
  accessModes:
    - {{ .Values.persistance.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistance.size }}