# Secret to access s3-compatible blob store
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  # See 
  credentials: |-
    [default]
    aws_access_key_id = {{ .Values.aws.accessKeyId }}
    aws_secret_access_key =  {{ .Values.aws.secretAccessKey }}
  config: |-
    [default]
    region = eu-central-1
    s3 =
        signature_version = s3v4