apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Values.nexus.name }}
  labels:
    app: {{ .Values.nexus.name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.nexus.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Values.nexus.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.nexus.name }}
      creationTimestamp: null
    spec:
      restartPolicy: {{ .Values.nexus.restartPolicy }}
      initContainers:
      - name: nexus-nfs
        image: busybox
        command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: pv-molgenis-nexus
          mountPath: "/nexus-data"
        {{- end }}
      containers:
      - name: {{ .Values.nexus.name }}
        image: "{{ .Values.nexus.image.repository }}:{{ .Values.nexus.image.tag }}"
        imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nexus.port.ui }}
        - containerPort: {{ .Values.nexus.port.docker }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: pv-molgenis-nexus
          mountPath: /nexus-data
        {{- end }}
#        livenessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.nexus.port.ui }}
#          initialDelaySeconds: 180
#          periodSeconds: 20
#          failureThreshold: 15
#          successThreshold: 1
#        readinessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.nexus.port.ui }}
#          initialDelaySeconds: 180
#          periodSeconds: 20
#          failureThreshold: 15
#          successThreshold: 1

    {{- if .Values.persistence.enabled }}
      volumes:
        - name: pv-molgenis-nexus
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claim }}
    {{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}