name: molgenis-sentry
home: https://jenkins.io/
version: 0.1.0
appVersion: ^0.5.0
description: Molgenis installation for the Sentry chart.
sources:
- https://github.com/molgenis/molgenis-ops-docker-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-docker-helm/master/charts/molgenis-sentry/catalogIcon-molgenis-sentry.png
maintainers:
- name: fdlk
- name: sidohaakma
