apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nexus
spec:
  rules:
  - host: registry.molgenis.org
    http:
      paths:
      - backend:
          serviceName: httpd
          servicePort: 80