apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nexus
  labels:
    app: nexus
    environment: production
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
      creationTimestamp: null
    spec:
      restartPolicy: Always
      containers:
      - name: nexus
        image: sonatype/nexus:latest
        ports:
        - containerPort: 8081
        - containerPort: 5000
