{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vue-pdfium.serviceAccountName" . }}
  labels:
{{ include "vue-pdfium.labels" . | indent 4 }}
{{- end -}}
