# Default values for molgenis-vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#abs details of the credentials to reach the azure backup storage
abs:
  # account is the name of the Storage account
  account: fdlkops
  # access key for the Storage account
  accessKey: xxxx
  # default cloud
  cloud: AzurePublicCloud

###
# All of the config variables related to setting up the etcd-operator
# If you want more information about the variables exposed, please visit:
#   https://github.com/kubernetes/charts/tree/master/stable/etcd-operator#configuration
###
etcd-operator:
  deployments:
    etcdOperator: true
    backupOperator: true
    restoreOperator: true
  serviceAccount:
    etcdOperatorServiceAccount:
      create: true
    backupOperatorServiceAccount:
      create: true
    restoreOperatorServiceAccount:
      create: true
  etcdOperator:
    image:
      tag: v0.9.2
  backupOperator:
    image:
      tag: v0.9.2
  restoreOperator:
    image:
      tag: v0.9.2

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - chart-example.local
  tls: []

