apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Values.jenkins.master.name }}
  labels:
    app: {{ .Values.jenkins.master.name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount}}
  strategy:
    type: {{ .Values.jenkins.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Values.jenkins.master.selector }}
  template:
      metadata:
        labels:
          app: {{ .Values.jenkins.master.name }}
        creationTimestamp: null
      spec:
        restartPolicy: {{ .Values.jenkins.restartPolicy }}
        containers:
          - name: {{ .Values.jenkins.master.name }}
            image: "{{ .Values.jenkins.master.image.repository }}:{{ .Values.jenkins.master.image.tag }}"
            imagePullPolicy: {{ .Values.jenkins.master.image.pullPolicy }}
            - env:
              - name: JENKINS_ADMIN_PASS
              - name: JENKINS_ADMIN_USER
            ports:
            - containerPort: {{ .Values.jenkins.master.port }}
            resources: {}
            volumeMounts:
            - name: jenkins-master-claim
              mountPath: /var/jenkins-home
            - name: jenkins-master-claim
              mountPath: /var/run/docker.sock
            volumes:
            - name: jenkins-master-claim
              persistentVolumeClaim:
                claimName: jenkins-master-claim
