elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch"
  esJavaOpts: "-Xmx2560m -Xms2560m -Dlog4j2.formatMsgNoLookups=true"
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      path.data: /usr/share/elasticsearch/data
      stack.templates.enabled: false
  resources:
    requests:
      cpu: "1000m"
      memory: "3Gi"
    limits:
      cpu: "1000m"
      memory: "3Gi"
  ingress:
    enabled: true
    annotations:
      ingressClassName: nginx
      nginx.ingress.kubernetes.io/whitelist-source-range: 195.169.22.0/23
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
    hosts:
      - host: logging.molgenis.org
        paths:
          - path: /
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: username
  authentication:
    username: xxxx
    password: xxxx
kibana:
  image: "docker.elastic.co/kibana/kibana"
  ingress:
    enabled: true
    annotations:
      ingressClassName: nginx
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2.molgenis.org/oauth2/start?rd=https://$host$request_uri
      nginx.ingress.kubernetes.io/auth-url: https://oauth2.molgenis.org/oauth2/auth
    hosts:
      - host: kibana.molgenis.org
        paths:
          - path: /
  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: username
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: password
