apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "molgenis-elasticsearch.fullname" . }}
  labels:
    app: {{ template "molgenis-elasticsearch.name" . }}
    chart: {{ template "molgenis-elasticsearch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "molgenis-elasticsearch.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "molgenis-elasticsearch.name" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- if .Values.esConfig }}
        configchecksum: {{ include (print .Template.BasePath "/config.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
    spec:
      containers:
        - name: elasticsearch
        {{- with .Values }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: {{ .clusterName }}
            {{- if .javaOpts  }}
            - name: ES_JAVA_OPTS
              value: "{{ .javaOpts }}"
            {{- end }}
            - name: discovery.type
              value: single-node
          ports:
            - containerPort: 9200
            - containerPort: 9300
          volumeMounts:
          - name: pv-elasticsearch
            mountPath: /usr/share/elasticsearch/data
          {{- range $path, $config := .esConfig }}
          - name: esconfig
            mountPath: /usr/share/elasticsearch/config/{{ $path }}
            subPath: {{ $path }}
          {{- end }}
          resources:
{{ toYaml .resources | indent 12 }}
        {{- end }}

      volumes:
        - name: pv-elasticsearch
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "molgenis-elasticsearch.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end -}}
        {{- if .Values.esConfig }}
        - name: esconfig
          configMap:
            name: {{ template "molgenis-elasticsearch.fullname" . }}-config
        {{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
