# Default values for molgenis.

replicaCount: 1

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  path: /
  hosts:
  - name: test.molgenis.org
  tls: []

molgenis:
  image:
    repository: registry.molgenis.org
    name: molgenis/molgenis-app
    tag: stable
    pullPolicy: Always
  adminPassword: admin
  javaOpts: "-Xmx1g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled"
  resources:
   limits:
    cpu: 1
    memory: 1250Mi
   requests:
    cpu: 200m
    memory: 1Gi
  services:
    opencpu:
      host: localhost
    elasticsearch:
      transportAddresses: localhost:9300
      clusterName: molgenis
    postgres:
      host: localhost
      scheme: molgenis
      user: molgenis
      password: molgenis

nodeSelector: {}

tolerations: []

affinity: {}
