{{- if eq .Values.environment "production" -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: molgenis-prometheus-cronjob
  labels:
    app: 'molgenis-prometheus'
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: "30 5 * * *"
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: get-targets
            image: alpine:latest
            env:
              - name: githubtoken
                valueFrom:
                  secretKeyRef:
                    name: molgenis-prometheus-cronjob-secrets
                    key: githubtoken
              - name: serverlistuser
                valueFrom: 
                  secretKeyRef:
                    name: molgenis-prometheus-cronjob-secrets
                    key: serverlistuser
              - name: serverlistpassword
                valueFrom:
                  secretKeyRef:
                    name: molgenis-prometheus-cronjob-secrets
                    key: serverlistpassword
            command: ["/bin/ash"]
            args: ["-c", "apk add curl bash && 
                    curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.5/bin/linux/amd64/kubectl && 
                    chmod +x kubectl && 
                    mv kubectl /usr/local/bin/kubectl && 
                    token=$(cat /run/secrets/kubernetes.io/serviceaccount/token) && 
                    wget {{ .Values.secret.githubtoken }}@raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-prometheus/scripts/targetWebGet.sh -O targetWebGet.sh && 
                    chmod +x targetWebGet.sh && 
                    bash targetWebGet.sh $(echo $githubtoken | base64 -d ) $(echo $serverlistuser | base64 -d ) $(echo $serverlistpassword | base64 -d ) &&
                    rm -rf /mnt/targetWebGet.sh"]
          serviceAccountName: update-configmap-bot
          restartPolicy: OnFailure
{{- end -}}
