{{- if eq .Values.environment "production" -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: molgenis-prometheus-cronjob
  labels:
    app: 'molgenis-prometheus'
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  schedule: "30 5 * * *"
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: get-targets
            image: alpine:latest
            envFrom:
            - secretRef:
                name: molgenis-prometheus-github-token
            command: ["/bin/ash"]
            args: ["-c", "apk add curl bash && 
                    curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.5/bin/linux/amd64/kubectl && 
                    chmod +x kubectl && 
                    mv kubectl /usr/local/bin/kubectl && 
                    TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token) && 
                    wget {{ .Values.secret.GITHUBTOKEN }}@raw.githubusercontent.com/christianhilbrands/molgenis-ops-helm/feat/link-checker-prometheus/charts/molgenis-prometheus/scripts/targetWebGet.sh -O targetWebGet.sh && 
                    chmod +x targetWebGet.sh && 
                    bash targetWebGet.sh ${GITHUBTOKEN} &&
                    rm -rf /mnt/targetWebGet.sh"]
          serviceAccountName: update-configmap-bot
          restartPolicy: OnFailure
{{- end -}}
