apiVersion: v1
kind: Secret
metadata:
  name: molgenis-prometheus-cronjob-secrets
type: Opaque
stringData: 
  githubtoken: {{ .Values.secret.githubtoken | b64enc | quote }}
  serverlistuser: {{ .Values.secret.serverlistuser | b64enc | quote }}
  serverlistpassword: {{ .Values.secret.serverlistpassword | b64enc | quote }}