apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmapUpdaterRoleBinder
subjects:
- kind: ServiceAccount
  name: update-configmap-bot
roleRef:
  kind: Role 
  name: updateConfigmapRole
  apiGroup: rbac.authorization.k8s.io