apiVersion: v1
kind: ConfigMap
metadata:
  name: targets-configmap
data:
  {{ if eq .Values.environment "production" -}}
  node-targets.yml: |
    #get replaced with master branch server via cronjob
  blackbox-targets.yml: |
    #get replaced with 2.0 branch servers via cronjob
  extra-targets.yml: |
    #get replaced with 1.0 branch servers via cronjob
  prod-target-list.yml: |
    - targets: ['molgenis23.gcc.rug.nl:9100']
      labels:
        project: "New server: MOLGENIS server list"
        branch: "2.0"
        type: "productie"
  {{ end -}}
