apiVersion: v1
kind: ConfigMap
metadata:
  name: targets-configmap
data:
  {{ if eq .Values.environment "production" -}}
  prod-http-list.yml: |
    #get replaced with master branch server via cronjob
  accept-http-list.yml: |
    #get replaced with 2.0 branch servers via cronjob
  test-http-list.yml: |
    #get replaced with 1.0 branch servers via cronjob
  prod-target-list.yml: |
    - targets: ['molgenis23.gcc.rug.nl:9100']
      labels:
        project: "New server: MOLGENIS server list"
        branch: "1.0"
        dtap: "productie"
  accept-target-list.yml: |
    #get replaced with 0.1 branch servers via cronjob
  test-target-list.yml: |
    #get replaced with 0.1 branch servers via cronjob    
  {{ end -}}
