apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-updater-role-binder
subjects:
- kind: ServiceAccount
  name: update-configmap-bot
roleRef:
  kind: Role 
  name: update-configmap-role
  apiGroup: rbac.authorization.k8s.io