apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  labels:
{{ include "lifelines-edge.labels" . | indent 4 }}
data:
  CRM_TOKEN_URL: {{ .Values.crm.oauth2.tokenUrl | quote }}
  USERNAME: {{ .Values.crm.oauth2.username | quote }}
  PROXY_TARGET: {{ .Values.molgenis.url | quote }}
