apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  labels:
{{ include "lifelines-edge.labels" . | indent 4 }}
data:
  MOLGENIS_URL: {{ .Values.molgenis.url | quote }}
  DATA_PLATFORM_URL: {{ .Values.dataPlatform.url | quote }}
