apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
  labels:
{{ include "lifelines-edge.labels" . | indent 4 }}
type: Opaque
stringData:
  DATA_PLATFORM_TOKEN: {{ .Values.dataPlatform.token | quote }}