apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
  labels:
{{ include "lifelines-edge.labels" . | indent 4 }}
type: Opaque
stringData:
  PASSWORD: {{ .Values.crm.oauth2.password | quote }}
  CLIENT_ID: {{ .Values.crm.oauth2.clientId | quote }}
  CLIENT_SECRET: {{ .Values.crm.oauth2.clientSecret | quote }}
  EDGE_USER_TOKEN: {{ .Values.molgenis.token | quote }}
  DATA_PLATFORM_TOKEN: {{ .Values.dataPlatform.token | quote }}