apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: etl-secret
data:
  staging-password: {{ .Values.etl.staging.password | b64enc }}
  catalogue-password: {{ .Values.etl.catalogue.password | b64enc }}