apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: etl-secret
data:
  staging-password: {{ .Values.etl.staging.password | b64enc }}
  production-password: {{ .Values.etl.production.password | b64enc }}