apiVersion: v1
kind: Service
metadata:
  name: {{ template "httpd.fullname" . }}
  labels:
    app: {{ template "httpd.name" . }}
    chart: {{ template "httpd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}

  selector:
    app: {{ template "httpd.name" . }}
    release: {{ .Release.Name }}
