apiVersion: v1
appVersion: "1.0"
description: Render PDFs using vue-pdfium
name: vue-pdfium
version: 0.1.1
home: https://github.com/molgenis/vue-pdfium
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/vue-pdfium/icon.png
maintainers:
- name: jvanveen
- name: fdlk
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
