apiVersion: v1
appVersion: "0.0.17"
description: A Helm chart for MOLGENIS Armadillo
name: molgenis-armadillo
version: 0.13.0
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
- https://github.com/molgenis/molgenis-service-armadillo.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-armadillo/catalogIcon-molgenis-armadillo.png
home: http://molgenis.org
maintainers:
- name: fdlk
- name: sidohaakma
