apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-custom-config
  labels:
    app: {{ template "frontend.name" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
data:
  custom.conf: |-
    {{ range $index, $location := .Values.proxy.custom -}}
    location /{{ $location.path }}/ {
      proxy_pass {{ $location.url }}/;
      {{- if and (index $location.unpkg) $location.unpkg -}}
      proxy_intercept_errors on;
      recursive_error_pages on;
      error_page 301 302 307 = @handle_redirect;
      {{- end -}}
    }
    {{ end }}