apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  generateName: vault-backup-
spec:
  clientTLSSecret: vault-etcd-client-tls
  etcdEndpoints:
    - https://vault-etcd-client:2379
  storageType: S3
  s3:
    awsSecret: aws
    path: vault/<specify name>
    endpoint: http://minio.minio.svc:9000
    forcePathStyle: true