apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-${SERVICE}
spec:
  rules:
  - host: ${SITENAME}
    http:
      paths:
      - backend:
          serviceName: ${SERVICE}
          servicePort: 80