grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.dev.molgenis.org
  persistence:
    enabled: false
  adminUser: admin

  ## Configure grafana datasources
  ## ref: http://docs.grafana.org/administration/provisioning/#datasources
  ##
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: k8-prometheus
        type: prometheus
        url: http://molgenis-prometheus-server.molgenis-prometheus.svc
        access: proxy
        isDefault: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      jenkins:
        gnetId: 306
        revision: 1
        datasource: k8-prometheus
      prometheus-stats:
        gnetId: 2
        revision: 2
        datasource: k8-prometheus
      kubernetes-cluster-monitoring:
        gnetId: 1621
        revision: 1
        datasource: k8-prometheus
      kubernetes-resource-requests:
        gnetId: 7187
        revision: 1
        datasource: k8-prometheus
      kubernetes-capacity:
        gnetId: 5309
        revision: 1
        datasource: k8-prometheus
      kubernetes-pods:
        gnetId: 6336
        revision: 1
        datasource: k8-prometheus
      kubernetes-cluster:
        gnetId: 6417
        revision: 1
        datasource: k8-prometheus
      jvm-micrometer:
        gnetId: 4701
        revision: 1
        datasource: k8-prometheus
      node-exporter:
        gnetId: 1860
        revision: 12
        datasource: k8-prometheus
      grafana:
        gnetId: 3590
        revision: 3
        datasource: k8-prometheus
      postgres:
        gnedId: 9628
        revision: 4
        datasource: k8-prometheus
      node-exporter-dashboard:
        url: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-grafana/dashboards/Node-Exporter-Dashboard.json
        datasource: k8-prometheus
      blackbox-exporter-overview:
        url: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-grafana/dashboards/Blackbox-Exporter-Overview.json
        datasource: k8-prometheus
      Total-UP-websites:
        url: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-grafana/dashboards/Total-UP-websites.json
        datasource: k8-prometheus
      ElasticSearch:
        url: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-grafana/dashboards/ElasticSearch.json
        datasource: k8-prometheus
      PostgreSQL-Performance-Analysis:
        url: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-grafana/dashboards/PostgreSQLPerformanceAnalysis.json
        datasource: k8-prometheus

  grafana.ini:
    log:
      level: debug
    auth.generic_oauth:
      enabled: true
      allow_sign_up: false
      client_id: xxxx
      client_secret: xxxx
      name: Auth0
      scopes: openid profile email
      auth_url: https://auth.molgenis.org/oauth2/authorize
      token_url: https://auth.molgenis.org/oauth2/token
      api_url: https://auth.molgenis.org/oauth2/userinfo
      use_pkce: true
      role_attribute_strict: true
      role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'viewer') && 'Viewer'

    server:
      root_url: "https://grafana.dev.molgenis.org"

    users:
      auto_assign_org_role: Editor

    smtp:
      enabled: true
      host: smtp.rug.nl:25
      from_address: grafana@molgenis.org

  nodeSelector:
    deployPod: "true"

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
