config:
  clientID: xxxx
  clientSecret: xxxx
  cookieSecret: "xxxx"
  configFile: |-
    pass_access_token = true

extraArgs:
  provider: "github"
  github-team: 2879410,2957876
  upstream: "file:///dev/null"
  http-address: "0.0.0.0:4180"
  whitelist-domain: .molgenis.org

replicaCount: 1

image:
  repository: "quay.io/pusher/oauth2_proxy"
  tag: "v3.2.0"
  pullPolicy: "IfNotPresent"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
