config:
  clientID: xxxx
  clientSecret: xxxx
  cookieSecret: "xxxx"
  configFile: |-
    pass_access_token = true

extraArgs:
  provider: "github"
  github-team: 2879410,2957876
  upstream: "file:///dev/null"
  http-address: "0.0.0.0:4180"
  whitelist-domain: .molgenis.org

image:
  repository: "quay.io/pusher/oauth2_proxy"
  tag: "v3.2.0"
  pullPolicy: "IfNotPresent"

authenticatedEmailsFile:
  enabled: false
  template: ""
  restricted_access: ""

service:
  type: ClusterIP
  port: 80
  annotations: {}
  # foo.io/bar: "true"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  path: /oauth2

resources: {}

priorityClassName: ""

tolerations: []

nodeSelector: {}

livenessProbe:
  enabled: true
  initialDelaySeconds: 0
  timeoutSeconds: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 0
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1

podAnnotations: {}
podLabels: {}
replicaCount: 1
