molgenis-oauth2:
  config:
    clientID: xxxx
    clientSecret: xxxx
    cookieSecret: "r3l8uTOUTZMPN99e6UxdSg=="
    configFile: |-
      pass_access_token = true

  extraArgs:
    provider: "github"
    github-org: "molgenis"
    upstream: "file:///dev/null"
    http-address: "0.0.0.0:4180"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    path: /oauth2
    hosts:
      - oauth2.edge.molgenis.org
  image:
    repository: "quay.io/pusher/oauth2_proxy"
    tag: "v3.2.0"