{{- if .Values.PipelineSecrets.Vault.Replace }}
apiVersion: v1
kind: Secret
metadata:
  name: molgenis-pipeline-vault-secret
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  token: {{ .Values.PipelineSecrets.Vault.Token | b64enc | quote }}
  addr: {{ .Values.PipelineSecrets.Vault.Addr | b64enc | quote }}
  skipVerify: {{ .Values.PipelineSecrets.Vault.SkipVerify | b64enc | quote }}
{{- end }}