{{- if .Values.PipelineSecrets.Env }}
apiVersion: v1
kind: Secret
metadata:
  name: molgenis-pipeline-env-secret
  labels:
    app: {{ template "jenkins.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  pgpPassphrase: {{ .Values.PipelineSecrets.Env.PGPPassphrase | b64enc | quote }}
  codecovToken: {{ .Values.PipelineSecrets.Env.CodecovToken | b64enc | quote }}
  githubToken: {{ .Values.PipelineSecrets.Env.GithubToken | b64enc | quote }}
  sonarToken: {{ .Values.PipelineSecrets.Env.SonarToken | b64enc | quote }}
{{- end }}