apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "molgenis-jenkins-dockerhub-secret"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations: {
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "user to authenticate against GOGS (git.webhosting.rug.nl)"
  }
type: Opaque
data:
  username: {{ "molgenisci" | b64enc | quote }}
  password: {{ .Values.PipelineSecrets.Env.DockerHubPassword | b64enc | quote }}