apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: {{ .Values.nexus.name }}
  labels:
    app: {{ .Values.nexus.name }}
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.nexus.strategy.type }}
  selector:
    matchLabels:
      app: {{ .Values.nexus.selector }}
  template:
    metadata:
      labels:
        app: {{ .Values.nexus.name }}
      creationTimestamp: null
    spec:
      securityContext:
#        runAsUser: 200
        fsGroup: 200
      volumes:
      - name: molgenis-nexus-data
        persistentVolumeClaim:
          claimName: molgenis-nexus-data
      restartPolicy: {{ .Values.nexus.restartPolicy }}
      containers:
      - name: {{ .Values.nexus.name }}
        image: "{{ .Values.nexus.image.repository }}:{{ .Values.nexus.image.tag }}"
        imagePullPolicy: {{ .Values.nexus.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nexus.port.ui }}
        - containerPort: {{ .Values.nexus.port.docker }}
        volumeMounts:
        - name: molgenis-nexus-data
          mountPath: "/nexus-data"
#        securityContext:
#          allowPrivilegeEscalation: false

