apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.backend.type }}
  ports:
    - name: {{ .Values.backend.name }}
      port: {{ .Values.backend.port }}
  selector:
    app: {{ .Values.backend.name }}
    release: {{ .Release.Name }}
