{{- if .Values.ingress.basicAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  labels:
    app: {{ template "frontend.name" . }}
    chart: {{ template "frontend.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  auth: {{ .Values.ingress.basicAuth.auth | b64enc | quote }}
{{- end }}
