{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ $.Release.Name }}-ingress"
  labels:
    app: {{ template "frontend.name" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
  annotations:
    {{- if .Values.ingress.tls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_intercept_errors on;
      recursive_error_pages on;
      error_page 403 404 500 = @molgenis;

      location @molgenis {
        proxy_pass {{ .Values.backend.url }};
      }      
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ $.Release.Name }}-{{ $.Values.service.name }}
            servicePort: {{ $.Values.service.port }}
  {{- end }}
{{- if .tls }}
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .name }}
    {{- end }}
    secretName: {{ .Values.ingress.tlsSecret }}
{{- end }}
---
{{- end }}