apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ template "frontend.name" . }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
data:
  backend.conf: |-
    location / {  
      proxy_pass {{ template "backend.servicename" . }};
      client_max_body_size 0;
    }
{{- if .Values.proxy.frontend }}
{{ toYaml .Values.proxy.frontend | indent 4  }}
{{- end -}}
