prometheus:
  alertmanager:
    nodeSelector:
      deployPod: "true"
    resources:
      limits:
        cpu: 10m
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 32Mi
  alertmanagerFiles:
    alertmanager.yml:
      global:
        slack_api_url: ''
      receivers:
        - name: default-receiver
          slack_configs:
            - channel: '#alerts'
              send_resolved: true
              text: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"
      route:
        group_wait: 10s
        group_interval: 5m
        receiver: default-receiver
        repeat_interval: 3h

  kubeStateMetrics:
    enabled: true
    nodeSelector:
      deployPod: "true"
    resources:
      limits:
        cpu: 20m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 128Mi

  nodeExporter:
    enabled: false
    nodeSelector:
      deployPod: "true"
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 30Mi

  pushgateway:
    nodeSelector:
      deployPod: "true"
    resources:
      limits:
        cpu: 10m
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 32Mi

  server:
    nodeSelector:
      deployPod: "true"
    resources:
      limits:
        cpu: 1
        memory: 6Gi
      requests:
        cpu: 1
        memory: 6Gi
    configMapOverrideName: "serverfiles-configmap"
    extraConfigmapMounts:
      - name: targets-configmap
        mountPath: /etc/configProm
        subPath: ""
        configMap: targets-configmap
        readOnly: true
  configmapReload:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
    extraConfigmapMounts:
      - name: targets-configmap
        mountPath: /etc/configProm
        subPath: ""
        configMap: targets-configmap
        readOnly: true
secret:
  GITHUBTOKEN: "xxxx"
environment: "development"
