{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "molgenis-armadillo-cohort.serviceAccountName" . }}
  labels:
{{ include "molgenis-armadillo-cohort.labels" . | indent 4 }}
{{- end -}}
