apiVersion: v1
kind: PersistentVolume
metadata:
  name: molgenis-nexus-data
  annotations:
    pv.beta.kubernetes.io/gid: "200"
  labels:
    name: nfs2
spec:
  storageClassName: nfs-class
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.64.12
    path: /gcc/molgenis/nexus
