apiVersion: v1
kind: Secret
metadata:
  name: fusion-postgresql
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
  rootpassword: {{ .Values.postgresql.password | b64enc | quote }}
