apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nexus
  labels:
    app: nexus
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: nexus
