apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nexus
  labels:
    app: nexus
spec:
  ports:
  - name: "ui"
    port: 8081
  - name: "docker"
    port: 5000
  selector:
    app: nexus
