apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "molgenis-datashield.fullname" . }}
  labels:
{{ include "molgenis-datashield.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "molgenis-datashield.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "molgenis-datashield.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MINIO_ACCESS_KEY
              value: {{ .Values.minio.accessKey }}
            - name: MINIO_SECRET_KEY
              value: {{ .Values.minio.secretKey }}
            - name: MINIO_URL
              value: http://{{ include "call-nested" (list $ "minio" "minio.fullname") }}
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: "server-config"
                  key: "application.json"
          {{ with .Values.server.config.spring.security.user }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
              httpHeaders:
                - name: Authorization
                  value: Basic {{ (printf "%s:%s" .name .password) | b64enc }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
              httpHeaders:
                - name: Authorization
                  value: Basic {{ (printf "%s:%s" .name .password) | b64enc }}
          {{- end }}
          resources:
{{ toYaml .Values.server.resources | nindent 12 }}
{{- if .Values.rserver.enabled }}
        - name: rserver
          image: {{ .Values.rserver.image.repository }}:{{ .Values.rserver.image.tag }}
          tag: 
          imagePullPolicy: Always
          ports:
            - containerPort: 6312
            - containerPort: 6311
          resources:
{{ toYaml .Values.rserver.resources | indent 12 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
