apiVersion: v2
description: JupyterHub
name: jupyterhub
version: 1.6.8
appVersion: 1.5.0
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
dependencies:
  - name: jupyterhub
    version: 1.2.0 
    repository: https://jupyterhub.github.io/helm-chart/
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/jupyterhub/catalogIcon-jupyterhub.png
home: https://jupyter.org
maintainers:
- name: sidohaakma
- name: Dick Postma
