apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.volumeName }}
  labels:
    name: nfs2
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy }}
  nfs:
    server: {{ .Values.persistence.server }}
    path: {{ .Values.persistence.mountPath }}
