transform:
  fullnameOverride: lifelines-transform
  schedule: 0 4 * * *
  image:
    repository: molgenis/molgenis-py-lifelines-transform
    tag: latest
    pullPolicy: Always
  config:
    actions:
      download: true
      upload: true
      transform: true
    catalog_folder: "latest"
    debug_mode: false
    molgenis:
      hostname: "http://molgenis:8080"
      token: "xxxx"
    src_dir: "data/catalog"
    s3:
      accessKey: "xxxx"
      bucket: "ll-catalogue-a"
      hostname: "s3.amazonaws.com"
      region: "eu-central-1"
      secretKey: "xxxx"
      secure: true
    target_dir: "data/generated"

vue-pdfium:
  fullnameOverride: "vue-pdfium"
  ingress:
    enabled: false
  image:
    repository: molgenis/vue-pdfium
    tag: latest
    pullPolicy: Always
  config:
    dev: false
    postLimit: "10mb"

lifelines-edge:
  fullnameOverride: lifelines-edge
  image:
    repository: molgenis/molgenis-node-lifelines-edge
    tag: latest
  molgenis:
    url: "http://molgenis:8080"
    token: ""
  dataPlatform:
    url: "https://acc-dp.lifelines.nl:8080"
    token: ""

molgenis:
  fullnameOverride: molgenis
  image:
    tag: "8.3.5"
    repository: "registry.hub.docker.com"
  mail:
    host: "smtp.rug.nl"
  sentry:
    dsn: "https://0145723ae6e44b8d90e58058ff301ba5@sentry.molgenis.org/2"
  molgenis-frontend:
    enabled: true
    environment: "test"
    image:
      tag: "8.2.4"
      repository: "registry.hub.docker.com"
    proxy:
      backend:
        service:
          enabled: false
        url: "http://molgenis:8080"
      experimental:
        - path: "@molgenis-experimental"
          url: https://unpkg.com/@molgenis-experimental
          unpkg: true
      custom:
        - path: "edge-server"
          url: "http://lifelines-edge/edge-server"
          unpkg: false
        - path: "vuepdf"
          url: "http://vue-pdfium/vuepdf"
          unpkg: false
        - path: "vuepdf-dev"
          url: "http://vue-pdfium/vuepdf-dev"
          unpkg: false
    ingress:
      basicAuth:
        enabled: true
        auth: "lifelines:$apr1$xxxxx"
        realm: "Authentication Required"
