apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "emx2.fullname" . }}-postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}
