apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: jenkins-master-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
