apiVersion: v1
appVersion: "9.1"
description: MOLGENIS - helm stack
name: molgenis
version: 1.15.8
sources:
- https://github.com/molgenis/molgenis-ops-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis/catalogIcon-molgenis.png
home: http://molgenis.org
maintainers:
- name: sidohaakma
- name: fdlk
- name: christianhilbrands
