dependencies:
  - name: molgenis-elasticsearch
    version: 2.1.1
    repository: https://registry.molgenis.org/repository/helm
    condition: molgenis-elasticsearch.enabled
  - name: molgenis-frontend
    version: 1.6.0
    repository: https://registry.molgenis.org/repository/helm
    condition: molgenis-frontend.enabled
  - name: postgresql
    version: 8.1.2
    repository: https://charts.helm.sh/stable
    condition: postgres.enabled
  - name: minio
    version: 8.0.10
    repository: https://helm.min.io/
    condition: minio.enabled
