apiVersion: v2
name: molgenis-jenkins
home: https://jenkins.io/
version: 1.16.0
appVersion: "2.332.2"
dependencies:
  - name: jenkins
    version: "3.12.1"
    repository: https://charts.jenkins.io
description: Molgenis installation for the jenkins chart.
sources:
  - https://github.com/molgenis/molgenis-ops-helm.git
icon: https://raw.githubusercontent.com/molgenis/molgenis-ops-helm/master/charts/molgenis-jenkins/catalogIcon-molgenis-jenkins.png
maintainers:
  - name: fdlk
  - name: sidohaakma
  - name: christianhilbrands
