apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  externalName: {{.Values.elasticsearch.host}}
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  type: ExternalName
