apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nexus
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: httpd
      creationTimestamp: null
    spec:
      containers:
      - image: sonatype/nexus3:latest
        name: nexus
        ports:
        - containerPort: 8081
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /nexus-data
          name: molgenis-nexus-data
      restartPolicy: Always
      volumes:
      - name: molgenis-nexus-data
        persistentVolumeClaim:
          claimName: molgenis-nexus-data
status: {}

